### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/specieshindex#12]
We should probably rename this repo `specieshindex` and then start a new one called `honours` which will have the analysis for your honours (and which uses the library `specieshindex`).  then we can seperate issues which affect all users of the `specieshindex` library from issues that only relate to your honours.

**Comment by itchyshin** [comment]
this is something you should so soon @jessicatytam  (as @wcornwell says putting CRAN is a big job so we should wait).

**Comment by jessicatytam** [comment]
ok i'll find out how to do this without messing up the files

**Comment by wcornwell** [comment]
looks like you did it!
