### ISSUE TITLE
add useful readme

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/specieshindex#13]
This can include stuff that a user might want to know about instillation, api keys, etc.  for api key there is a nice thing here: https://github.com/muschellij2/rscopus, so can just link to that

also readme can include the cool artwork that is now in the vignette.

**Comment by jessicatytam** [comment]
is this like a simplified version of the vignette?

**Comment by wcornwell** [comment]
yes, super simplified. 

1. just one section on what does the package do (conceptually)
2. how to install it (link to rscopus for all the api key stuff)
3. super simple example
4. link to vignette

pretty good model here: https://github.com/muschellij2/rscopus

**Comment by wcornwell** [comment]
nice one @jessicatytam
