### ISSUE TITLE
hexsticker

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/specieshindex#14]
it's possible we might need a super cool hexsticker for this project:
https://github.com/GuangchuangYu/hexSticker

**Comment by itchyshin** [comment]
@jessicatytam - it will be great if you can use these animal characters - it is fairly easy to make - we can probably buy somoe stickers for you!

**Comment by jessicatytam** [comment]
looks like a fun project, i'll have a read and come up some designs

**Comment by itchyshin** [comment]
@jessicatytam - put a screenshot in this issue!

**Comment by jessicatytam** [comment]
![image](https://user-images.githubusercontent.com/51732676/93408728-a1d5f700-f8d8-11ea-8412-db2234fd07b2.png)

**Comment by itchyshin** [comment]
Ah, this is what you meant! - but you could probably create it in RStudio? - and screenshot it here? @jessicatytam

**Comment by jessicatytam** [comment]
it was working when i knitted it as a .rmd file in rstudio

**Comment by jessicatytam** [comment]
![image](https://user-images.githubusercontent.com/51732676/93409256-d1d1ca00-f8d9-11ea-8dce-4b67ab48afda.png)

**Comment by wcornwell** [comment]
super cute!

yeah getting it to show up in readme is tricky--the image has to be in the repository with a relative path.  example here.  or you can send the jpg and i can fix it up.

**Comment by itchyshin** [comment]
@jessicatytam - I want to jpg too - so we can order stickers!

**Comment by jessicatytam** [comment]
yay it's working now thanks!

**Comment by itchyshin** [comment]
@wcornwell @jessicatytam @mlagisz - something all of us to think about - 'specieshindex' too long or is it good as it is. Or should we shorten it??? something like 'sppH' or are we all happy - I guess a descriptive title is a good one

**Comment by wcornwell** [comment]
I like longer personally.  Too many acronyms in the world already.

**Comment by wcornwell** [comment]
Nice one.  @itchyshin file is here: https://github.com/jessicatytam/specieshindex/blob/master/README_files/figure-gfm/stickerfile.png for your sticker order

**Comment by itchyshin** [comment]
Thanks! @wcornwell  - OK - I think a longer one is good then

**Comment by wcornwell** [comment]
🎆

**Comment by wcornwell** [comment]
@itchyshin https://elifesciences.org/articles/60080

**Comment by itchyshin** [comment]
@wcornwell  - a great little paper!
