### ISSUE TITLE
domain restriction function

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/specieshindex#16]
filtering to only papers that have a given word e.g. "conservation", "development", "genomics", etc.

**Comment by jessicatytam** [comment]
So the fetch functions will only download the title of the papers (no abstracts or keywords), I'm thinking we can do one of the following:
1. only analyse the title from the citation data collected from the fetch functions (I don't think this is a good idea) or
2. change the fetch functions and make them download the abstracts and keywords too or
3. create a new function that connects to Scopus and look at all of title+abstract+keywords, but doesn't collect any data (this will be quite tedious, but I think this is the best option)

Some other things to think about:
- do we want to know just the number of papers in each domain? or do we want to know the specific papers too?
- how many domains should we include and which ones?
- what about the papers without any specific domains? 'others'?

**Comment by wcornwell** [comment]
Maybe a version of (3).  I think it would just have to query SCOPUS abstracts for "Phascolarctos cinereus" AND "conservation"?

**Comment by mlagisz** [comment]
> Maybe a version of (3). I think it would just have to query SCOPUS abstracts for "Phascolarctos cinereus" AND "conservation"?

maybe even allow term variants, e.g. "conserv*"
or expand it to:  "Phascolarctos cinereus" AND ("conserv*" OR "protect*")

**Comment by wcornwell** [comment]
Or maybe even let the user specify the domain?

```
FetchSpT(genus="Phascolarctos",species="cinereus",domain="conserv*")
```

**Comment by wcornwell** [comment]
@jessicatytam also done?
