### ISSUE TITLE
JOSS markdown description

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/specieshindex#17]

**Comment by wcornwell** [comment]
https://joss.readthedocs.io/en/latest/submitting.html

**Comment by jessicatytam** [comment]
should I push it to this repo?

**Comment by wcornwell** [comment]
yeah i think so, at least for now

**Comment by wcornwell** [comment]
looks like it has to be:

> Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software

https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles
