### ISSUE TITLE
warning from Allindices

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/specieshindex#18]
Not sure what's causing this:

<img width="822" alt="Screen Shot 2020-11-20 at 3 50 25 pm" src="https://user-images.githubusercontent.com/5534161/99760615-3282ba80-2b48-11eb-98a3-69c27d2e98ff.png">

**Comment by jessicatytam** [comment]
it should be fixed now

**Comment by wcornwell** [comment]
yup! 🎆
