### ISSUE TITLE
Tasks / meeting notes

### ISSUE THREAD

**Issue by jessicatytam** [jessicatytam/specieshindex#2]
**Meeting date: 10 March**
- [x] Find a reliable database with all mammalian species

- paper comparing databases: https://academic.oup.com/jmammal/article/99/1/1/4834091
- database (2017): https://mammaldiversity.org/

- [x] H-index definition / formula vs number of papers

- some help: https://subjectguides.uwaterloo.ca/calculate-academic-footprint/YourHIndex
https://www.muhclibraries.ca/wp-content/uploads/2015/07/H-Index_Jun2015-EN-FINAL-1.pdf

- [x] Scopus vs wos

- papers comparing scopus & wos: https://www.sciencedirect.com/science/article/pii/S1751157718303249
http://www.istl.org/18-spring/refereed2.html

- [x] Ways to catagorise different species
- By region / taxon / usage

- [x] R packages

- rscopus (connects to scopus): https://cran.r-project.org/web/packages/rscopus/rscopus.pdf
- API key

**Comment by jessicatytam** [comment]
Meeting date: 7 April

- [ ] Questions / hypothesis

- [ ] Get API key

- [ ] Create a function that queries for 1 species

**Comment by wcornwell** [comment]
Links from meeting: 

- https://stackoverflow.com/questions/50099885/scopus-api-number-of-requests-remaining-for-the-week 

- https://dev.elsevier.com/api_key_settings.html

**Comment by jessicatytam** [comment]
**Meeting date: 12 May**

- BEES0006 Special Project discussion

**Comment by jessicatytam** [comment]
**Meeting date: 9 June**

- [ ] Proposal

- [ ] H-index codes

**Comment by mlagisz** [comment]
Meeting date: 9 June
- decided to have regular meetings on Tuesdays at 1:30pm (check with @wcornwell if suitable)
- @wcornwell Will - please send example of a proposal to Jess, and any other information on writing th eproposal
- @itchyshin requested @jessicatytam Jess to follow BEES43041 assessment format for now
- tentative deadline 26 June 2020
- @jessicatytam  to give us a proposal outline before the next meeting (16th June)
- plan how the method will be validated and how the benefits can be quantified (e.g. time saved)
- re-check technical limitations of API - check again how to get all the complete records for a given species (currently seems to be stuck at max. of 25)
- if it is possible to only download the TC field? - test citation_retrieval function from Rscopus package

**Comment by mlagisz** [comment]
- use testing package: http://r-pkgs.had.co.nz/tests.html
 - how to write R package vignette?
 - check and set limits on numbers of records to work with, e.g. if more than 2000 records, only first 2000 get retrieved?
 - create working example (code + data) for everybody to play with
 - meet up on campus for a work session - Losia and Jess

**Comment by jessicatytam** [comment]
- Address the comments in the proposal; to be checked by @wcornwell by the end of the week

- Proposal deadline postponed to 30/6

- Meeting with @mlagisz tmr at uni

**Comment by jessicatytam** [comment]
**Meeting date: 30 June**

- @itchyshin is marking the proposal today

- make a plan for all of the functions that need to be coded

- functions for the indices have been coded, need to work on functions that can recall citation data from scopus

**Comment by itchyshin** [comment]
@jessicatytam - I will do a proper making so give me more than a day - I will do this in next few days and get approval from both @mlagisz and @wcornwell - I will send my evaluation by the end of the week to them

**Comment by jessicatytam** [comment]
![Uploading IMG_20200706_164333.jpg…]()

**Comment by jessicatytam** [comment]
![IMG_20200706_164333](https://user-images.githubusercontent.com/51732676/86583945-745efa00-bfc7-11ea-9b69-c1fffb9583d4.jpg)

**Comment by jessicatytam** [comment]
**Meeting date: 7 July**

- Presentation on 10 August 10am during lab meeting

- Fetch function: now working for species, can try downloading papers with spp name in the abstract & keywords; add API key as a parameter; need to work on remedying the limitations (i.e. too many records), create batches?

- Work on documentation

**Comment by jessicatytam** [comment]
**Meeting date: 14 July**

- Start working on the vignette, download miktex

- Fix loop, start with small chunks of records and add text to make checks in the loop

- Meeting next week? maybe

**Comment by jessicatytam** [comment]
**Meeting date: 21 July**

- Add references to the description

- Vignette deadline on 14 August; export to html

- Could add a data file to package as an example

- @wcornwell will help with the testing

**Comment by jessicatytam** [comment]
Meeting date: 28 July

- Hide API Key

- Fix scopus request to get more records

- JOSS peer-reviewed journal for packages

- Do frequent checks in R

- Have to eventually change repo name to package name

- Bring presentation slides next week

**Comment by jessicatytam** [comment]
**Meeting date: 4 August**

- Package name too long, will have to change it

- Add references to vignette; can use BibTeX

- Email updated slides by Friday

- Email vignette draft next Tuesday; deadline is flexible

**Comment by jessicatytam** [comment]
Meeting date: 11 August

- Email final draft on 14 Aug; deadline on 17 Aug

- Add references to vignette, can add pictures
