### ISSUE TITLE
add badges / shields

### ISSUE THREAD

**Issue by jessicatytam** [jessicatytam/specieshindex#20]
i think we need to setup something under the 'actions' tab for the R-CMD check badge to work

**Comment by wcornwell** [comment]
yeah that's right check: https://github.com/r-lib/actions/

**Comment by wcornwell** [comment]
also info there about how to do #15

**Comment by wcornwell** [comment]
i *think* the stuff you'll need is here: https://github.com/r-lib/actions/tree/master/examples#quickstart-ci-workflow
