### ISSUE TITLE
Beta testing

### ISSUE THREAD

**Issue by jessicatytam** [jessicatytam/specieshindex#23]
Max
- [x] asked
- [x] tested

Hamza
- [x] asked
- [ ] tested

Sophie
- [x] asked
~~- [ ] tested~~ (she won't be on campus and doesn't have a VPN)

Charley
- [x] asked
- [x] tested

Pietro
- [x] asked
- [ ] tested 

Some marine people from Suhelen's lab
- [x] asked
- [ ] tested

**Comment by wcornwell** [comment]
from charley: 

How long ago was the instructions written? Im getting surprisingly higher publication numbers than the example on git

Actually they aren't too much bigger, but the figure examples on git dont seem to reflect the data? eg the output data says Koala has the highest h-index but figure 1 on git shows it is the lowest.

**Comment by wcornwell** [comment]
also charley raised the issue in #26 and #25
