### ISSUE TITLE
base

### ISSUE THREAD

**Issue by jessicatytam** [jessicatytam/specieshindex#36]
https://github.com/ropensci/rbace

**Comment by jessicatytam** [comment]
requested api access

**Comment by jessicatytam** [comment]
IP address has now been whitelisted so i can work on a loop

**Comment by jessicatytam** [comment]
looks like unsw's IP address has changed, should I get the new one whitelisted again or focus on the plotting function for now?

**Comment by mlagisz** [comment]
please apply again for whitelisting with new IP - it might take a while so in the meantime you could work on plotting functions

**Comment by jessicatytam** [comment]
the whole IP address group has been whitelisted now, so hopefully no need to request again

**Comment by jessicatytam** [comment]
i ran `httr::POST(url = "https://api.base-search.net/cgi-bin/BaseHttpSearchInterface.fcgi", body = "dctitle:Macropus rufus")` and 
`httr::content(base, as = "text", encoding = "application/xml")` 
using the api but got this error which i don't understand and can't seem to find anything on google / stackoverflow
`<?xml version="1.0" encoding="utf-8"?>
<error>Parameter 'func' not found!</error>`

**Comment by jessicatytam** [comment]
but the request is successful

Response [https://api.base-search.net/cgi-bin/BaseHttpSearchInterface.fcgi]
  Date: 2021-05-04 02:01
  Status: 200
  Content-Type: text/xml; charset=UTF-8
  Size: 82 B
`<?xml version="1.0" encoding="utf-8"?>`

**Comment by jessicatytam** [comment]
looks like it's working now
