### ISSUE TITLE
new SourceType function

### ISSUE THREAD

**Issue by jessicatytam** [jessicatytam/specieshindex#39]
I've added a new function SourceType(), which counts the number of items for each type of document (e.g. book chapter, journal article, conference proceeding, etc.)
should I remove TotalArt(), TotalRev(), and ARRatio() since SourceType() does the same thing but can also detect other document types?

**Comment by mlagisz** [comment]
yes, you could remove these functions - does this new function work with all databases/sources?

**Comment by jessicatytam** [comment]
Yup it seems to be working

**Comment by jessicatytam** [comment]
replaced TotalArt(), TotalRev(), and ARRatio() with SourceType()
