### ISSUE TITLE
function for plot

### ISSUE THREAD

**Issue by jessicatytam** [jessicatytam/specieshindex#40]
write functions that will makes plots of the data collected

**Comment by jessicatytam** [comment]
![image](https://user-images.githubusercontent.com/51732676/116959314-9953f480-ace0-11eb-9b25-ffca51a5488d.png)
makes a ggplot that looks like this

**Comment by itchyshin** [comment]
nice @jessicatytam! 

Maybe make the dots a bit bigger?

**Comment by jessicatytam** [comment]
![image](https://user-images.githubusercontent.com/51732676/116965787-fa37f880-acf1-11eb-8884-9865f1810154.png)
like this?

**Comment by itchyshin** [comment]
great @jessicatytam
