### ISSUE TITLE
[JOSS REVIEW] Functionality - error with Fetch functions Bad Request (HTTP 400) 

### ISSUE THREAD

**Issue by DrMattG** [jessicatytam/specieshindex#46]
[Review = https://github.com/openjournals/joss-reviews/issues/3776]
The Fetch functions (db="scopus") give an Bad Request (HTTP 400) error.  

`library(specieshindex)

CountSpT(db = "scopus", genus = "Bettongia", species = "penicillata")

#> [1] "Species found on CoL, ITIS, NCBI, or EoL."
#> [1] 45

FetchSpT(db = "scopus", genus = "Bettongia", species = "penicillata")

#> [1] "Species found on CoL, ITIS, NCBI, or EoL."
#> [1] "45 records found."
#> [1] "starting iteration:  0  Note: iteration size is  1000  records, which runs of 200 records inside each iteration."
#> [1] "Fetching records now."
#> The query list is:
#> list(query = "TITLE(\"Bettongia penicillata\")", count = 200, 
#>     start = 0, view = "STANDARD")
#> $query
#> [1] "TITLE(\"Bettongia penicillata\")"
#> 
#> $count
#> [1] 200
#> 
#> $start
#> [1] 0
#> 
#> $view
#> [1] "STANDARD"
#> 
#> Response [https://api.elsevier.com/content/search/scopus?query=TITLE%28%22Bettongia%20penicillata%22%29&count=200&start=0&view=STANDARD]
#>   Date: 2021-10-19 07:25
#>   Status: 400
#>   Content-Type: application/json;charset=UTF-8
#>   Size: 131 B
#> Error in get_results(query, start = init_start, count = count, verbose = verbose, : Bad Request (HTTP 400).

CountGenusT(db = "scopus", genus = "Bettongia")

#> [1] "Genus found on CoL, ITIS, NCBI, or EoL."
#> [1] 122

FetchGenusT(db = "scopus", genus = "Bettongia")

#> [1] "Genus found on CoL, ITIS, NCBI, or EoL."
#> [1] "122 records found."
#> [1] "starting iteration:  0  Note: iteration size is  1000  records, which runs of 200 records inside each iteration."
#> [1] "Fetching records now."
#> The query list is:
#> list(query = "TITLE(\"Bettongia\")", count = 200, start = 0, 
#>     view = "STANDARD")
#> $query
#> [1] "TITLE(\"Bettongia\")"
#> 
#> $count
#> [1] 200
#> 
#> $start
#> [1] 0
#> 
#> $view
#> [1] "STANDARD"
#> 
#> Response [https://api.elsevier.com/content/search/scopus?query=TITLE%28%22Bettongia%22%29&count=200&start=0&view=STANDARD]
#>   Date: 2021-10-19 07:25
#>   Status: 400
#>   Content-Type: application/json;charset=UTF-8
#>   Size: 131 B
#> Error in get_results(query, start = init_start, count = count, verbose = verbose, : Bad Request (HTTP 400).
#`

**Comment by jessicatytam** [comment]
Seems to be working now, I've forgotten to replace `sp` with `genus` when copying things over to `FetchGenusT()` and `FetchGenusTAK()`. Do let me know if that has fixed things.

**Comment by jessicatytam** [comment]
I think your institution might not be a Scopus/Elsevier paid subscriber, which means they don't allow paper extraction but you can still count the number of papers.

**Comment by DrMattG** [comment]
Okay - As long as the function works for others then I am happy
