### ISSUE TITLE
Implement a secure way to provide credentials in sessions 

### ISSUE THREAD

**Issue by jessicatytam** [jessicatytam/specieshindex#52]
https://db.rstudio.com/best-practices/managing-credentials/ 
this might help

**Comment by Bisaloo** [comment]
Yes! That would be a great improvement.

Please note that httr also provides a guide on this matter: 

- https://httr.r-lib.org/articles/secrets.html
- https://httr.r-lib.org/articles/api-packages.html#authentication

**Comment by jessicatytam** [comment]
I've added instructions in both the README and vignette on how to this securely (this section here: https://github.com/jessicatytam/specieshindex#using-your-api-key-securely), but it's not part of a function that's within the package. Will this be sufficient?

**Comment by jessicatytam** [comment]
done
