### ISSUE TITLE
Undocumented arguments in documentation object 'Fetch'  and Count'   ‘level’

### ISSUE THREAD

**Issue by wcornwell** [jessicatytam/specieshindex#56]
Can you check the documentation on this @jessicatytam, i think this is something that came from the function re-naming process?

**Comment by wcornwell** [comment]
@jessicatytam I removed the input `level` from `fetch` and `count` since it didn't look like it was being used.  is this what you had in mind?

**Comment by jessicatytam** [comment]
ah ok thanks, yup i was trying to remove `level` since i've now combined species-level & genus-level searches into one function

**Comment by jessicatytam** [comment]
i'll check again tmr to make sure

**Comment by jessicatytam** [comment]
looks good now
