### ISSUE TITLE
More info on Connecting to BASE 

### ISSUE THREAD

**Issue by fontikar** [jessicatytam/specieshindex#59]
I navigated to the BASE website but there wasn't too intuitive as to how to get 'whitelisted' 
More info in a vignette would be good! Step by step with screenshots!

**Comment by jessicatytam** [comment]
i think the only way to do it is to contact them and send them a request message, i've linked it in the documentation (link: https://www.base-search.net/about/en/contact.php) but i'll see what i can add to make it easier to understand

**Comment by jessicatytam** [comment]
done
